name: brainwavesocialapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.5
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.2
  json_annotation: ^4.9.0
  google_sign_in: ^6.2.1
  firebase_cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.7
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.9.2
  cupertino_icons: ^1.0.8
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
